name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.0' 

      # Build the .NET application
      - name: Build
        run: dotnet build --configuration Release

      # Package the application as a Docker container
      - name: Build Docker image
        uses: azure/docker-login@v1
        with:
          login-server: hrsample.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t <your-container-registry>/<image-name>:latest
          docker push <your-container-registry>/<image-name>:latest

      # Install Helm
      #- name: Install Helm
      #  run: |
      #    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      #    chmod 700 get_helm.sh
      #    ./get_helm.sh

      # Configure kubectl
      #- name: Configure kubectl
      #  uses: azure/k8s-set-context@v1
      #  with:
      #    kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      # Deploy to AKS using Helm
      #- name: Helm deploy
      #  run: |
      #   helm upgrade --install <release-name> <path-to-helm-chart> --set image.repository=<your-container-registry>/<image-name>,image.tag=latest --namespace <namespace>
